version: 2.1

parameters:
  BUILD_NAME:
    type: string
    default: "tower-defense"
  UNITY_ACTIVATION_FILE:
    type: string
    default: "./unity3d.alf"

jobs:
  authenticate:
    docker:
      - image: gableroux/unity3d:2019.3.2f1
    environment:
      TEST_PLATFORM: editmode
    steps:
      - checkout
      - chmod +x ./ci/get_activation_file.sh && ./ci/get_activation_file.sh
      - store_artifacts:
          path: << pipeline.parameters.UNITY_ACTIVATION_FILE >>
          destination: license
  test:
    docker:
      - image: gableroux/unity3d:2019.3.2f1
    steps:
      - run: chmod +x ./ci/before_script.sh && ./ci/before_script.sh
      - run: chmod +x ./ci/test.sh && ./ci/test.sh
      - run: echo "Hello World!"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - authenticate
      - test
